/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompanyRouteImport } from './routes/_authenticated/company'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users/$userId'
import { Route as AuthenticatedCompanyStaffRouteImport } from './routes/_authenticated/company/staff'
import { Route as AuthenticatedCompanySettingsRouteImport } from './routes/_authenticated/company/settings'
import { Route as AuthenticatedCompanyMembershipsRouteImport } from './routes/_authenticated/company/memberships'
import { Route as AuthenticatedCompanyLocationsRouteImport } from './routes/_authenticated/company/locations'
import { Route as AuthenticatedCompanyLocationsAddRouteImport } from './routes/_authenticated/company/locations/add'
import { Route as AuthenticatedCompanyLocationsLocationIdRouteImport } from './routes/_authenticated/company/locations/$locationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompanyRoute = AuthenticatedCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const AuthenticatedCompanyStaffRoute =
  AuthenticatedCompanyStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanySettingsRoute =
  AuthenticatedCompanySettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyMembershipsRoute =
  AuthenticatedCompanyMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyLocationsRoute =
  AuthenticatedCompanyLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyLocationsAddRoute =
  AuthenticatedCompanyLocationsAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AuthenticatedCompanyLocationsRoute,
  } as any)
const AuthenticatedCompanyLocationsLocationIdRoute =
  AuthenticatedCompanyLocationsLocationIdRouteImport.update({
    id: '/$locationId',
    path: '/$locationId',
    getParentRoute: () => AuthenticatedCompanyLocationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/company': typeof AuthenticatedCompanyRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/company/locations': typeof AuthenticatedCompanyLocationsRouteWithChildren
  '/company/memberships': typeof AuthenticatedCompanyMembershipsRoute
  '/company/settings': typeof AuthenticatedCompanySettingsRoute
  '/company/staff': typeof AuthenticatedCompanyStaffRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/company/locations/$locationId': typeof AuthenticatedCompanyLocationsLocationIdRoute
  '/company/locations/add': typeof AuthenticatedCompanyLocationsAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/company': typeof AuthenticatedCompanyRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/company/locations': typeof AuthenticatedCompanyLocationsRouteWithChildren
  '/company/memberships': typeof AuthenticatedCompanyMembershipsRoute
  '/company/settings': typeof AuthenticatedCompanySettingsRoute
  '/company/staff': typeof AuthenticatedCompanyStaffRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/company/locations/$locationId': typeof AuthenticatedCompanyLocationsLocationIdRoute
  '/company/locations/add': typeof AuthenticatedCompanyLocationsAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/company': typeof AuthenticatedCompanyRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/company/locations': typeof AuthenticatedCompanyLocationsRouteWithChildren
  '/_authenticated/company/memberships': typeof AuthenticatedCompanyMembershipsRoute
  '/_authenticated/company/settings': typeof AuthenticatedCompanySettingsRoute
  '/_authenticated/company/staff': typeof AuthenticatedCompanyStaffRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/company/locations/$locationId': typeof AuthenticatedCompanyLocationsLocationIdRoute
  '/_authenticated/company/locations/add': typeof AuthenticatedCompanyLocationsAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/company'
    | '/dashboard'
    | '/settings'
    | '/users'
    | '/company/locations'
    | '/company/memberships'
    | '/company/settings'
    | '/company/staff'
    | '/users/$userId'
    | '/company/locations/$locationId'
    | '/company/locations/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account'
    | '/company'
    | '/dashboard'
    | '/settings'
    | '/users'
    | '/company/locations'
    | '/company/memberships'
    | '/company/settings'
    | '/company/staff'
    | '/users/$userId'
    | '/company/locations/$locationId'
    | '/company/locations/add'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/account'
    | '/_authenticated/company'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/company/locations'
    | '/_authenticated/company/memberships'
    | '/_authenticated/company/settings'
    | '/_authenticated/company/staff'
    | '/_authenticated/users/$userId'
    | '/_authenticated/company/locations/$locationId'
    | '/_authenticated/company/locations/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company': {
      id: '/_authenticated/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthenticatedCompanyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/company/staff': {
      id: '/_authenticated/company/staff'
      path: '/staff'
      fullPath: '/company/staff'
      preLoaderRoute: typeof AuthenticatedCompanyStaffRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/settings': {
      id: '/_authenticated/company/settings'
      path: '/settings'
      fullPath: '/company/settings'
      preLoaderRoute: typeof AuthenticatedCompanySettingsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/memberships': {
      id: '/_authenticated/company/memberships'
      path: '/memberships'
      fullPath: '/company/memberships'
      preLoaderRoute: typeof AuthenticatedCompanyMembershipsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/locations': {
      id: '/_authenticated/company/locations'
      path: '/locations'
      fullPath: '/company/locations'
      preLoaderRoute: typeof AuthenticatedCompanyLocationsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/locations/add': {
      id: '/_authenticated/company/locations/add'
      path: '/add'
      fullPath: '/company/locations/add'
      preLoaderRoute: typeof AuthenticatedCompanyLocationsAddRouteImport
      parentRoute: typeof AuthenticatedCompanyLocationsRoute
    }
    '/_authenticated/company/locations/$locationId': {
      id: '/_authenticated/company/locations/$locationId'
      path: '/$locationId'
      fullPath: '/company/locations/$locationId'
      preLoaderRoute: typeof AuthenticatedCompanyLocationsLocationIdRouteImport
      parentRoute: typeof AuthenticatedCompanyLocationsRoute
    }
  }
}

interface AuthenticatedCompanyLocationsRouteChildren {
  AuthenticatedCompanyLocationsLocationIdRoute: typeof AuthenticatedCompanyLocationsLocationIdRoute
  AuthenticatedCompanyLocationsAddRoute: typeof AuthenticatedCompanyLocationsAddRoute
}

const AuthenticatedCompanyLocationsRouteChildren: AuthenticatedCompanyLocationsRouteChildren =
  {
    AuthenticatedCompanyLocationsLocationIdRoute:
      AuthenticatedCompanyLocationsLocationIdRoute,
    AuthenticatedCompanyLocationsAddRoute:
      AuthenticatedCompanyLocationsAddRoute,
  }

const AuthenticatedCompanyLocationsRouteWithChildren =
  AuthenticatedCompanyLocationsRoute._addFileChildren(
    AuthenticatedCompanyLocationsRouteChildren,
  )

interface AuthenticatedCompanyRouteChildren {
  AuthenticatedCompanyLocationsRoute: typeof AuthenticatedCompanyLocationsRouteWithChildren
  AuthenticatedCompanyMembershipsRoute: typeof AuthenticatedCompanyMembershipsRoute
  AuthenticatedCompanySettingsRoute: typeof AuthenticatedCompanySettingsRoute
  AuthenticatedCompanyStaffRoute: typeof AuthenticatedCompanyStaffRoute
}

const AuthenticatedCompanyRouteChildren: AuthenticatedCompanyRouteChildren = {
  AuthenticatedCompanyLocationsRoute:
    AuthenticatedCompanyLocationsRouteWithChildren,
  AuthenticatedCompanyMembershipsRoute: AuthenticatedCompanyMembershipsRoute,
  AuthenticatedCompanySettingsRoute: AuthenticatedCompanySettingsRoute,
  AuthenticatedCompanyStaffRoute: AuthenticatedCompanyStaffRoute,
}

const AuthenticatedCompanyRouteWithChildren =
  AuthenticatedCompanyRoute._addFileChildren(AuthenticatedCompanyRouteChildren)

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCompanyRoute: typeof AuthenticatedCompanyRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCompanyRoute: AuthenticatedCompanyRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
